### ISSUE TITLE
Make sure we're supporting enough of the Vec interface

### ISSUE THREAD

**Issue by asajeffrey** [asajeffrey/presort#5]
We are intending this for use in display list construction in Servo, we should make sure that we're supporting enough of the Vec interface that we can swap out Vec in DisplayList.

cc @kyleheadley

**Comment by kyleheadley** [comment]
Using a singleton type instead for the DisplayList vector gives errors of the following types when compiling servo:

## general
- indexing
- type mismatch when passing as a parameter

## traits
- HeapSizeOf, Serialize, Deserialize
- Iterator

## methods
- len
- sort_by

Using the following code reduced the errors to only those of the general form above:

```
#[derive(HeapSizeOf, Deserialize, Serialize)]
struct NewDL;

impl NewDL {
    pub fn len(&self) -> usize {0}
    pub fn sort_by<T, F>(&mut self, compare: F)
    where F: FnMut(&T, &T) -> Ordering {}
}

impl<'a> Iterator for &'a NewDL {
    type Item = DisplayItem;

    fn next(&mut self) -> Option<DisplayItem> {None}

}

#[derive(HeapSizeOf, Deserialize, Serialize)]
pub struct DisplayList {
    pub list: NewDL,
    pub offsets: FnvHashMap<StackingContextId, StackingContextOffsets>,
    pub root_stacking_context: StackingContext,
}
```

**Comment by asajeffrey** [comment]
Can you give an example of "type mismatch when passing as a parameter"?

Can we implement `Index` for `NewDL` to get rid of the indexing errors?

**Comment by asajeffrey** [comment]
The traits `HeapSizeOf, Deserialize, Serialize` are a bit annoying, as implementing them requires the `presort` crate depending on `heapsize` and `serde`, or using features.

**Comment by kyleheadley** [comment]
I didn't know about `Index`, I'll add that.

The type errors are for when`displaylist.list` is passed as a parameter to fn's requiring a `Vec<>`. There will have to be changed in the servo code.

**Comment by asajeffrey** [comment]
Hmm, that's annoying, we've got functions which expect a `Vec<T>` rather than `&[T]`?

**Comment by asajeffrey** [comment]
Can you pastecloud or gist the errors?

**Comment by kyleheadley** [comment]
Looks like it's only one occurrence, and the rest are because I didn't return a properly constructed `DisplayListItem`.

`let mut list = mem::replace(&mut self.list, Vec::new());` 
at around line 244 in the original `displaylist/mod.rs`

**Comment by asajeffrey** [comment]
Oh but that one's in the `DisplayList` code, so we're okay.

**Comment by kyleheadley** [comment]
oh, and DisplayList.new(), which is an easy fix as well

**Comment by asajeffrey** [comment]
The indexing is into the sorted vector, yes?

**Comment by kyleheadley** [comment]
This code gives only the two errors noted above:

```
use std::ops::Index;
#[derive(HeapSizeOf, Deserialize, Serialize)]
struct NewDL;

impl NewDL {
    pub fn len(&self) -> usize {0}
    pub fn sort_by<T, F>(&mut self, compare: F)
    where F: FnMut(&T, &T) -> Ordering {}
}

impl<'a> Iterator for &'a NewDL {
    type Item = DisplayItem;

    fn next(&mut self) -> Option<DisplayItem> {None}

}

impl Index<usize> for NewDL {
    type Output = DisplayItem;

    fn index<'a>(&'a self, _index: usize) -> &'a DisplayItem {panic!("no item ready")}
}

#[derive(HeapSizeOf, Deserialize, Serialize)]
pub struct DisplayList {
    pub list: NewDL,
    pub offsets: FnvHashMap<StackingContextId, StackingContextOffsets>,
    pub root_stacking_context: StackingContext,
}
```

**Comment by kyleheadley** [comment]
I'll make the indexing fail again to check that it's in a place that assumes the list is sorted

**Comment by kyleheadley** [comment]
Indexing is always into the sorted list, it's used for paint and the webrender traversal.

**Comment by asajeffrey** [comment]
Good. One annoyance is that display list building is using `sort_by` rather than `sort`. Do you know how tricky it would be to provide an appropriate `Ord` impl so we could use `sort`?

**Comment by kyleheadley** [comment]
docs say `Ord` requires `cmp`, `partial_cmp`, and `eq`. I don't think those would be appropriate to implement, since the sorting depends on the current stacking contexts. Can't we just reuse the code from display_list/mod.rs:243?

**Comment by asajeffrey** [comment]
Argh, the sort order depends on the stacking context? Oh rats, this makes it really difficult to memoize.

**Comment by kyleheadley** [comment]
Yeah, the display list items are basically leaves in a stacking context tree. It's _that_ tree that is sorted (by z-index and spec), but separately for each type. It's possible there's enough info cached during the initial stacking context sort to fully sort the display list items. I don't recall offhand if values or references are cached. I can look into it.

**Comment by kyleheadley** [comment]
Looks like every `DisplayItem` requires a `StackingContextId`, so it _would_ be appropriate to implement `Ord`. However, the data defining the sort order is external to the vec, stored in `Displaylist::offsets` or the flow root.

**Comment by asajeffrey** [comment]
I added support for heapsize and serde.
